/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
    // 这里就是定义docs目录下的文档上边框布局
    // By default, Docusaurus generates a sidebar from the docs folder structure
//  tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
//   projectSidebar: [{type: 'autogenerated', dirName: 'AnalysisProject'}],
    middlewareSidebar: [{type: 'autogenerated', dirName: 'coreMiddleware'}],
    jdkSidebar: [{type: 'autogenerated', dirName: 'JavaDocs'}],
    devopsSidebar: [{type: 'autogenerated', dirName: 'DevOps'}],

    // But you can create a sidebar manually
    projectSidebar: [
        {
            type: 'doc',
            id: 'AnalysisProject/Analysis Project是什么', // 指向 'docs/introduction.md'
            label: 'Analysis Project是什么',
        },
        {
            type: 'doc',
            id: 'AnalysisProject/直观的质检系统设计', // 指向 'docs/introduction.md'
            label: '直观的质检系统设计',
        },
        {
            type: 'category',
            label: '一个更好的系统设计',
            items: [
                'AnalysisProject/一个更好的系统设计/超越流式遍历', // 指向 'tutorial-advanced/perform-setup.md'
                'AnalysisProject/一个更好的系统设计/系统构成', // 指向 'tutorial-advanced/use-hooks.md'
                'AnalysisProject/一个更好的系统设计/核心组件', // 指向 'tutorial-advanced/use-hooks.md'
            ],
        },
        {
            type: 'doc',
            id: 'AnalysisProject/关于项目演进的个人思考', // 指向 'docs/introduction.md'
            label: '关于项目演进的个人思考',
        },
    ],
};

export default sidebars;
