/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // 这里就是定义docs目录下的文档上边框布局
  // By default, Docusaurus generates a sidebar from the docs folder structure
//  tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
  projectSidebar: [{type: 'autogenerated', dirName: 'AnalysisProject'}],
  middlewareSidebar: [{type: 'autogenerated', dirName: '核心组件'}],
  jdkSidebar: [{type: 'autogenerated', dirName: 'Java相关'}],
  devopsSidebar: [{type: 'autogenerated', dirName: 'DevOps'}],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

export default sidebars;
